version: "3"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'SA_PASSWORD=123456(!)Password'
      ACCEPT_EULA: 'Y'